### ISSUE TITLE
jboss.eap.common-directories output hard to read/use

### ISSUE THREAD

**Issue by kdelee** [quipucords/rho#409] opened 2017-10-25 16:57 UTC
## Specify type:
- Enhancement

### Bug severity (if applicable):
- Medium
___

## Description:
The current output is very verbose and it would be hard for a user to find useful information in it.
___

### Version of rho:
[ 0.29 ]

### Expected behavior:
I remember Dan talking about us only outputting the directories that we found, that is what I expected when I ran the scan with the jboss facts.

### Actual behavior:
Sample output of a machine on which a common directory *was* found: (emphasis mine, notice how hard it would be to read with out the bold)

jboss.eap.common-directories
| ------- |
/app/jboss not found;/app/jboss6 not found;/home/jboss/EAP not found;/home/jboss/EAP-6.3 not found;/JBossAS not found;/JBossEAP not found;/opt/app/jboss not found;/opt/deploy/jboss not found;/opt/hpom/share/jboss not found;/opt/jboss not found;**/opt/rh/eap7 found**;/usr/local/jee/jboss not found;/usr/log/jboss-as not found;/usr/share/jbossas not found;/var/log/jboss-as not found

### Steps to reproduce:
Scan a machine with the RPM install of JBoss EAP 7 installed and running -- this is installed in one of the "common directories". 

### Environment information:
Provide detailed information on the *scanning* and *target* systems (if applicable); see example below.

Type            | Operating System | OS Version | Python Version | Virtualization
--------------- | ---------------- | ---------- | -------------- | --------------
Scanning System | Fedora            | 25        | 3.6            | Bare Metal
Target System   | RHEL             | 7.4        | 2.X          | ESXi

**Comment by noahl** [comment] 2017-10-25 17:23
This is a duplicate of #391 . You are right that we are going to only output the directories found; I just haven't done it yet.

**Closed as completed by noahl** 2017-10-25 17:23 UTC

**Comment by kdelee** [comment] 2017-10-27 17:01
@noahl thanks for catching the duplicate!
